## in memory h2 database config
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9080
  address: 0.0.0.0
  servlet:
    contextPath: /person-rest-api/v1

logging:
  level:
    root: INFO

management:
  security:
    enabled: false




